"use client";
import { useApi } from "@/hooks/useApi";
import { formatCurrency, SHOOT_STATUS, TASK_STATUS } from "@/lib/constants";
import { Skeleton } from "@/components/ui/Skeleton";

type Analytics={clients:{total:number;new:number};shoots:{total:number;byStatus:Record<string,number>};galleries:{total:number};revenue:{paid:number;pending:number;overdue:number;byMonth:{month:string;paid:number}[]};tasks:{byStatus:Record<string,number>};proposals:{conversionRate:number}};
export default function AnalyticsPage(){const {data,loading,error,refetch}=useApi<Analytics>("/api/analytics");if(loading)return <Skeleton className="h-[520px]"/>;if(error)return <Retry error={error} retry={refetch}/>;if(!data)return null;const max=Math.max(1,...data.revenue.byMonth.map(x=>x.paid));return <div className="space-y-8"><header><p className="text-xs uppercase tracking-[.25em] text-gold">Performance</p><h1 className="text-3xl text-white font-semibold mt-2">Analytics do estúdio</h1></header><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[["Receita",formatCurrency(data.revenue.paid)],["Clientes",data.clients.total],["Ensaios",data.shoots.total],["Conversão",`${data.proposals.conversionRate}%`]].map(([l,v])=><article key={l} className="p-5 rounded-2xl bg-white/[.02] border border-white/5"><p className="text-xs text-noir-500">{l}</p><p className="text-2xl text-white font-semibold mt-2">{v}</p></article>)}</div><section className="p-6 rounded-2xl bg-white/[.02] border border-white/5"><h2 className="text-white font-medium mb-6">Receita recebida por mês</h2><div className="h-56 flex items-end gap-3">{data.revenue.byMonth.map(x=><div key={x.month} className="flex-1 h-full flex flex-col justify-end items-center gap-2"><span className="text-[10px] text-noir-500">{formatCurrency(x.paid)}</span><div className="w-full max-w-16 bg-gold/70 rounded-t" style={{height:`${Math.max(3,(x.paid/max)*85)}%`}}/><span className="text-xs text-noir-500">{x.month.slice(5)}</span></div>)}</div></section><div className="grid lg:grid-cols-2 gap-6"><Breakdown title="Ensaios por status" values={data.shoots.byStatus} labels={SHOOT_STATUS}/><Breakdown title="Tarefas por status" values={data.tasks.byStatus} labels={TASK_STATUS}/></div></div>}
function Breakdown({title,values,labels}:{title:string;values:Record<string,number>;labels:Record<string,{label:string;textColor:string}>}){return <section className="p-5 rounded-2xl bg-white/[.02] border border-white/5"><h2 className="text-white font-medium mb-4">{title}</h2>{Object.entries(values).map(([k,v])=><div className="flex justify-between py-2 border-b border-white/5" key={k}><span className={`text-sm ${labels[k]?.textColor||"text-noir-400"}`}>{labels[k]?.label||k}</span><b className="text-white">{v}</b></div>)}</section>}
function Retry({error,retry}:{error:string;retry:()=>void}){return <div className="text-center py-20"><p className="text-red-400">{error}</p><button onClick={retry} className="mt-4 bg-gold text-black px-4 py-2 rounded-lg">Tentar novamente</button></div>}
