"use client";
import { useState } from "react";
import { useApi } from "@/hooks/useApi";
import { getInitials } from "@/lib/constants";
import { Skeleton } from "@/components/ui/Skeleton";
type Session={user:{name:string;email:string;phone?:string;role:string;avatar?:string};studio?:{name?:string;slug?:string;city?:string;phone?:string;plan?:string;brandColor?:string}};
const TABS=["Perfil","Estúdio","Marca","Plano","Notificações","Segurança"];
export default function SettingsPage(){const [tab,setTab]=useState("Perfil");const {data,loading,error,refetch}=useApi<Session>("/api/auth/me");if(loading)return <Skeleton className="h-[520px]"/>;if(error)return <div className="text-center py-20"><p className="text-red-400">{error}</p><button onClick={refetch} className="mt-4 bg-gold text-black px-4 py-2 rounded-lg">Tentar novamente</button></div>;const u=data?.user,s=data?.studio;return <div><header className="mb-8"><p className="text-xs uppercase tracking-[.25em] text-gold">Conta</p><h1 className="text-3xl text-white font-semibold mt-2">Configurações</h1></header><nav className="flex flex-wrap gap-1 mb-8 border-b border-white/5 pb-3">{TABS.map(x=><button key={x} onClick={()=>setTab(x)} className={`px-4 py-2 rounded-lg text-sm ${tab===x?"bg-gold/10 text-gold":"text-noir-500 hover:text-white"}`}>{x}</button>)}</nav>{tab==="Perfil"?<Card title="Dados pessoais"><div className="flex gap-4 items-center mb-6"><div className="w-16 h-16 rounded-full bg-gold/15 grid place-items-center text-gold text-xl font-bold">{getInitials(u?.name||"Usuário")}</div><div><p className="text-white">{u?.name}</p><p className="text-xs text-noir-500">{u?.role}</p></div></div><Fields values={[["Nome",u?.name],["Email",u?.email],["Telefone",u?.phone]]}/></Card>:tab==="Estúdio"?<Card title="Dados do estúdio"><Fields values={[["Nome",s?.name],["Identificador",s?.slug],["Cidade",s?.city],["Telefone",s?.phone]]}/></Card>:tab==="Marca"?<Card title="Identidade visual"><Fields values={[["Cor principal",s?.brandColor||"#c9a96e"],["Nome público",s?.name]]}/></Card>:tab==="Plano"?<Card title="Plano atual"><p className="text-2xl text-gold capitalize">{s?.plan||"Não informado"}</p></Card>:<Card title={tab}><p className="text-sm text-noir-400">Estas preferências permanecem visuais nesta etapa e serão conectadas em uma atualização futura.</p></Card>}</div>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="max-w-2xl p-6 bg-white/[.02] border border-white/5 rounded-2xl"><h2 className="text-white font-semibold mb-5">{title}</h2>{children}</section>}
function Fields({values}:{values:(string|undefined)[][]}){return <div className="grid md:grid-cols-2 gap-4">{values.map(([l,v])=><label key={l} className="text-xs text-noir-500">{l}<input defaultValue={v||""} className="mt-1 w-full bg-white/[.03] border border-white/10 rounded-lg px-4 py-2.5 text-sm text-white"/></label>)}</div>}
