"use client";

import { useState } from "react";
import { useApi, useApiMutation } from "@/hooks/useApi";
import { formatCurrency, formatDate, PROPOSAL_STATUS } from "@/lib/constants";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Select } from "@/components/ui/Select";
import { Modal } from "@/components/ui/Modal";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { TableSkeleton } from "@/components/ui/Skeleton";
import { EmptyState } from "@/components/ui/EmptyState";
import { useToast } from "@/components/ui/Toast";

type Proposal={id:string;clientName:string;service:string;total:number;status:string;validUntil?:string;createdAt:string};
type Client={id:string;name:string};
type Item={description:string;quantity:string;unitPrice:string};
const emptyItem=():Item=>({description:"",quantity:"1",unitPrice:""});
const initial={clientId:"",service:"",package:"",validUntil:"",notes:"",discount:"",items:[emptyItem()]};

export default function ProposalsPage(){
  const [open,setOpen]=useState(false); const [form,setForm]=useState(initial); const [errors,setErrors]=useState<Record<string,string>>({}); const [deleting,setDeleting]=useState<Proposal|null>(null);
  const {showToast}=useToast(); const list=useApi<Proposal[]>("/api/proposals?pageSize=100"); const clients=useApi<Client[]>("/api/clients?pageSize=100");
  const create=useApiMutation<Record<string,unknown>>("/api/proposals","POST"); const remove=useApiMutation(`/api/proposals/${deleting?.id||"pending"}`,"DELETE");
  const subtotal=form.items.reduce((sum,x)=>sum+(Number(x.quantity)||0)*(Number(x.unitPrice)||0)*100,0); const discount=Math.round((Number(form.discount)||0)*100); const total=Math.max(0,subtotal-discount);
  function setItem(index:number,key:keyof Item,value:string){setForm({...form,items:form.items.map((x,i)=>i===index?{...x,[key]:value}:x)})}
  function validate(){const e:Record<string,string>={};if(!form.clientId)e.clientId="Cliente é obrigatório";if(!form.service.trim())e.service="Serviço é obrigatório";if(!form.validUntil)e.validUntil="Validade é obrigatória";if(!form.items.length||form.items.some(x=>!x.description.trim()||Number(x.quantity)<1))e.items="Preencha todos os itens";setErrors(e);return !Object.keys(e).length}
  async function save(){if(!validate())return;const c=clients.data?.find(x=>x.id===form.clientId);const body={...form,clientName:c?.name,discount,items:form.items.map(x=>({description:x.description,quantity:Number(x.quantity),unitPrice:Math.round(Number(x.unitPrice)*100)})),status:"draft"};const r=await create.mutate(body);if(r.success){showToast("Proposta criada!","success");setOpen(false);setForm(initial);setErrors({});list.refetch()}else setErrors({_general:r.error||"Erro ao criar proposta"})}
  async function send(p:Proposal){const r=await fetch(`/api/proposals/${p.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"sent"})}).then(x=>x.json());showToast(r.success?"Proposta enviada!":r.error||"Erro",r.success?"success":"error");if(r.success)list.refetch()}
  async function del(){const r=await remove.mutate();showToast(r.success?"Proposta excluída!":r.error||"Erro",r.success?"success":"error");if(r.success){setDeleting(null);list.refetch()}}
  return <><div><header className="flex justify-between items-end mb-8"><div><p className="text-xs uppercase tracking-[.25em] text-gold">Comercial</p><h1 className="text-3xl text-white font-semibold mt-2">Propostas</h1></div><Button onClick={()=>setOpen(true)}>Nova proposta</Button></header>{list.loading?<TableSkeleton/>:list.error?<Retry error={list.error} retry={list.refetch}/>:list.data?.length?<div className="space-y-3">{list.data.map(p=>{const info=PROPOSAL_STATUS[p.status as keyof typeof PROPOSAL_STATUS];return <article key={p.id} className="p-4 bg-white/[.02] border border-white/5 rounded-xl flex flex-col md:flex-row md:items-center gap-4"><div className="flex-1"><h2 className="text-sm text-white">{p.service}</h2><p className="text-xs text-noir-500">{p.clientName} · {formatDate(p.validUntil||p.createdAt)}</p></div><strong className="text-white">{formatCurrency(p.total)}</strong><span className={`text-xs ${info?.textColor}`}>{info?.label||p.status}</span>{p.status==="draft"&&<Button size="sm" onClick={()=>send(p)}>Enviar</Button>}<Button size="sm" variant="danger" onClick={()=>setDeleting(p)}>Excluir</Button></article>})}</div>:<EmptyState title="Nenhuma proposta" description="Crie uma proposta para um cliente." action={<Button onClick={()=>setOpen(true)}>Nova proposta</Button>}/>}</div>
  <Modal isOpen={open} onClose={()=>setOpen(false)} title="Nova proposta" size="xl"><div className="space-y-4">{errors._general&&<p className="text-sm text-red-400">{errors._general}</p>}<div className="grid sm:grid-cols-2 gap-4"><Select label="Cliente *" error={errors.clientId} value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})} placeholder="Selecione" options={(clients.data||[]).map(x=>({value:x.id,label:x.name}))}/><Input label="Serviço *" error={errors.service} value={form.service} onChange={e=>setForm({...form,service:e.target.value})}/><Input label="Pacote" value={form.package} onChange={e=>setForm({...form,package:e.target.value})}/><Input label="Validade *" error={errors.validUntil} type="date" value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})}/></div><div><div className="flex justify-between items-center mb-2"><label className="text-xs text-noir-400">Itens da proposta *</label><Button size="sm" variant="secondary" onClick={()=>setForm({...form,items:[...form.items,emptyItem()]})}>Adicionar item</Button></div>{errors.items&&<p className="text-xs text-red-400 mb-2">{errors.items}</p>}<div className="space-y-2">{form.items.map((item,i)=><div key={i} className="grid grid-cols-[1fr_72px_110px_36px] gap-2"><Input placeholder="Descrição" value={item.description} onChange={e=>setItem(i,"description",e.target.value)}/><Input type="number" min="1" value={item.quantity} onChange={e=>setItem(i,"quantity",e.target.value)}/><Input type="number" min="0" step="0.01" placeholder="R$" value={item.unitPrice} onChange={e=>setItem(i,"unitPrice",e.target.value)}/><button aria-label="Remover item" disabled={form.items.length===1} onClick={()=>setForm({...form,items:form.items.filter((_,x)=>x!==i)})} className="text-red-400 disabled:opacity-30">×</button></div>)}</div></div><div className="grid sm:grid-cols-2 gap-4"><Input label="Desconto (R$)" type="number" min="0" value={form.discount} onChange={e=>setForm({...form,discount:e.target.value})}/><div className="rounded-lg bg-white/[.03] border border-white/5 p-3 text-sm"><div className="flex justify-between text-noir-500"><span>Subtotal</span><span>{formatCurrency(subtotal)}</span></div><div className="flex justify-between text-white font-semibold mt-2"><span>Total</span><span>{formatCurrency(total)}</span></div></div></div><label className="text-xs text-noir-400">Notas<textarea value={form.notes} maxLength={2000} onChange={e=>setForm({...form,notes:e.target.value})} className="mt-1 w-full min-h-24 bg-white/[.03] border border-white/10 rounded-lg p-3 text-white"/></label></div><div className="flex justify-end gap-2 mt-6"><Button variant="secondary" onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={save} isLoading={create.loading}>Criar proposta</Button></div></Modal>
  <ConfirmDialog isOpen={!!deleting} onClose={()=>setDeleting(null)} onConfirm={del} title="Excluir proposta" message="Esta ação não pode ser desfeita." isLoading={remove.loading}/></>;
}
function Retry({error,retry}:{error:string;retry:()=>void}){return <div className="text-center py-16"><p className="text-red-400">{error}</p><Button className="mt-4" onClick={retry}>Tentar novamente</Button></div>}
