"use client";
import { useState } from "react";
import { useApi } from "@/hooks/useApi";
import { formatDate, SHOOT_STATUS } from "@/lib/constants";
import { Skeleton } from "@/components/ui/Skeleton";
import { Modal } from "@/components/ui/Modal";
type Shoot={id:string;name:string;clientName?:string;date:string;startTime?:string;location?:string;status:string};
const DAYS=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];
export default function CalendarPage(){const now=new Date();const [cursor,setCursor]=useState(new Date(now.getFullYear(),now.getMonth(),1));const [selected,setSelected]=useState<Shoot|null>(null);const {data,loading,error,refetch}=useApi<Shoot[]>("/api/shoots?pageSize=100");if(loading)return <Skeleton className="h-[600px]"/>;if(error)return <Retry error={error} retry={refetch}/>;const year=cursor.getFullYear(),month=cursor.getMonth(),first=new Date(year,month,1).getDay(),count=new Date(year,month+1,0).getDate();const cells=[...Array(first).fill(null),...Array.from({length:count},(_,i)=>i+1)];const shoots=data||[];return <div><header className="flex items-end justify-between gap-4 mb-8"><div><p className="text-xs uppercase tracking-[.25em] text-gold">Agenda</p><h1 className="text-3xl text-white font-semibold mt-2">{cursor.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</h1></div><div className="flex gap-2"><button onClick={()=>setCursor(new Date(year,month-1,1))} className="btn">←</button><button onClick={()=>setCursor(new Date(year,month+1,1))} className="btn">→</button></div></header><div className="grid grid-cols-7 border border-white/5 rounded-2xl overflow-hidden">{DAYS.map(d=><div key={d} className="p-3 text-center text-xs text-noir-500 bg-white/[.03]">{d}</div>)}{cells.map((day,i)=><div key={i} className="min-h-28 p-2 border-t border-r border-white/5 bg-white/[.01]">{day&&<><span className="text-xs text-noir-500">{day}</span>{shoots.filter(s=>{const d=new Date(s.date);return d.getFullYear()===year&&d.getMonth()===month&&d.getDate()===day}).map(s=><button key={s.id} onClick={()=>setSelected(s)} className="block w-full text-left mt-1 p-2 rounded bg-gold/10 border border-gold/10 text-[11px] text-gold truncate">{s.startTime||""} {s.name}</button>)}</>}</div>)}</div><Modal isOpen={!!selected} onClose={()=>setSelected(null)} title={selected?.name}>{selected&&<div className="space-y-3 text-sm"><p className="text-noir-400">Cliente: <span className="text-white">{selected.clientName||"Não informado"}</span></p><p className="text-noir-400">Data: <span className="text-white">{formatDate(selected.date,"withTime")}</span></p><p className="text-noir-400">Local: <span className="text-white">{selected.location||"Não informado"}</span></p><p className={SHOOT_STATUS[selected.status as keyof typeof SHOOT_STATUS]?.textColor}>{SHOOT_STATUS[selected.status as keyof typeof SHOOT_STATUS]?.label||selected.status}</p></div>}</Modal></div>}
function Retry({error,retry}:{error:string;retry:()=>void}){return <div className="text-center py-20"><p className="text-red-400">{error}</p><button onClick={retry} className="btn mt-4">Tentar novamente</button></div>}
